### ISSUE TITLE
REST API availability

### ISSUE THREAD

**Issue by fvdm** [erfgoed-en-locatie/artsholland-platform#1]
Hi, is the REST API still available?
The endpoints seem to have changed or something.

http://code.waag.org/artsholland-dev/api/#rest

**Comment by tomdemeyer** [comment]
The data is no longer available, so we had to close the endpoint, unfortunately..
best,

--

Tom Demeyer
Waag Society
http://waag.org

**Comment by fvdm** [comment]
Okay, then I'll deprecate my node module.
